use_frameworks!

target 'AALocalizationKit_Example' do
  pod 'AALocalizationKit', :path => '../'
  pod 'AAPickerView'

  target 'AALocalizationKit_Tests' do
    inherit! :search_paths

    
  end
end
